name: Django-DSFR CI for python 3.12+

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: ðŸ Set up Python ${{ matrix.python-version }} with uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: ðŸ‘· Install Dependencies
      run: |
        uv sync --no-group dev
    - name: ðŸš§ Check pending migrations
      run: |
        uv run python manage.py makemigrations --check --dry-run --noinput
    - name: ðŸ§ª Run Tests - Django 4
      run: |
        uv run python manage.py test
    - name: ðŸ§ª Run Tests - Django 5
      run: |
        uv add "django>=5.0,<6.0"
        uv run python manage.py test
    - name: ðŸ§ª Run Tests - Django 6
      run: |
        sed -i 's/requires-python = "<4.0,>=3.10"/requires-python = "<4.0,>=3.12"/g' pyproject.toml
        uv add "django>=6.0"
        uv run python manage.py test
