name: Django-DSFR CI for python 3.10+

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: ğŸ Set up Python ${{ matrix.python-version }} with uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: ğŸ‘· Install Dependencies
      run: |
        uv sync --no-group dev
    - name: ğŸš§ Check pending migrations
      run: |
        uv run python manage.py makemigrations --check --dry-run --noinput
    - name: ğŸ§ª Run Tests - Django 4
      run: |
        uv run python manage.py test
    - name: ğŸ§ª Run Tests - Django 5
      run: |
        uv add django@^5.0
        uv run python manage.py test
