name: Django-DSFR deploy documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: github.repository_owner == 'numerique-gouv'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: ğŸ“” Install just
      uses: extractions/setup-just@v2
    - name: ğŸ Set up Python ${{ matrix.python-version }} with uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: ğŸ‘· Install Dependencies
      run: |
        uv sync
    - name: ğŸ“„ Build docs
      run: |
        just export_static
        touch docs/django-dsfr/.nojekyll
    - name: ğŸš€ Deploy Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages     # <- Branche sur laquelle seront commitÃ©s les fichiers
        FOLDER: docs/django-dsfr/  # <- Dossier contenant notre documentation gÃ©nÃ©rÃ©e
