name: Publish package on PyPI
on:
  # Trigger the workflow on new releases
  release:
    types:
      - created

jobs:
  publish:
    name: Build and publish package on PyPI
    runs-on: ubuntu-latest
    permissions:
      # For PyPI's trusted publishing.
      id-token: write
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: ğŸ Set up Python ${{ matrix.python-version }} with uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: ğŸ‘· Install Dependencies
      run: |
        uv sync --no-group dev
    - name: ğŸ“¦ Build and publish package
      run: |
        uv build
        uv publish
